updater:
  enableProvider: true
  clientPath: client
  manifestPath: client_manifest.json
  listenIp: 0.0.0.0
  listenPort: 80
  requireUpdater: true
  kickMessage: SkyCraft Updater is required to enter this server